spring.application.name=apiwatch
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5440/apiwatch_db
spring.datasource.username=apiwatch_user
spring.datasource.password=apiwatch_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never